// Code generated by "nlpc --module=languages --input=languages.json --target=languages_repo.go". DO NOT EDIT.

package stringer

const (
	English Language = iota
	Russian
)

type lt struct {
	name, native, iso1, iso3 OL32
}

var (
	__lt_lst = []lt{
		{name: 0x00000007, native: 0x0007000e, iso1: 0x000e0010, iso3: 0x00100013},
		{name: 0x0013001a, native: 0x001a0028, iso1: 0x0028002a, iso3: 0x002a002d},
	}
	__lt_buf = []byte("EnglishEnglishenengRussianРусскийrurus")
)
